DROP DATABASE IF EXISTS server_db;
CREATE DATABASE server_db;

USE server_db;

CREATE TABLE dummy_server(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
server_name VARCHAR(30) NOT NULL,
status VARCHAR(30) NOT NULL,
timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
